/**
 * Build-time SEO data layer for sitemap, prerender, and IndexNow scripts.
 *
 * Reads from `scripts/data/route-snapshot.json` (generated by
 * `scripts/generate-route-snapshot.mjs`) so the Node build pipeline never
 * directly imports TypeScript. Falls back to a minimal hard-coded route set
 * if the snapshot is missing — allowing legacy `seo:indexnow` invocations
 * to still work without the full TS-aware pipeline.
 */
import { readFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const rootDir = dirname(dirname(fileURLToPath(import.meta.url)));

export const site = {
  name: "SceneShift",
  host: "sceneshift.org",
  url: "https://sceneshift.org",
  email: "contact@sceneshift.org",
  phone: "+15155795378",
  phoneLabel: "(515) 579-5378",
  region: "Ames, Iowa",
  ogImage:
    "/assets/images/page-title/des-moines-iowa-usa-capitol-building-on-a-misty-2026-03-24-11-27-15-utc.jpg",
  indexNowKey: "b44f0c99429d41d9896cfd3cfc07933e",
};

/**
 * Existing site routes that ship indexed regardless of the SEO snapshot.
 * The snapshot adds the new SEO/AIO routes on top of these.
 */
const baseCanonicalRoutes = [
  {
    path: "/",
    key: "home17",
    title: "AI CRM Automation for Small Businesses | SceneShift",
    description:
      "SceneShift helps Iowa small businesses capture more leads, answer faster, automate follow-up, and build practical AI-powered CRM workflows.",
    priority: "1.0",
    changefreq: "weekly",
    schemaType: "ProfessionalService",
  },
  {
    path: "/about-us",
    key: "about-us",
    title: "About SceneShift | Small Business AI Automation in Iowa",
    description:
      "Learn how SceneShift helps independent businesses in Ames and across Iowa respond faster, follow up consistently, and stay easy to choose.",
    priority: "0.8",
    changefreq: "monthly",
    schemaType: "AboutPage",
  },
  {
    path: "/pricing",
    key: "pricing",
    title: "AI Automation Pricing for Small Businesses | SceneShift",
    description:
      "Compare SceneShift packages for missed-call text back, unified inboxes, AI reception, web chat, review generation, and sales follow-up automation.",
    priority: "0.8",
    changefreq: "weekly",
    schemaType: "Service",
  },
  {
    path: "/contact",
    key: "contact",
    title: "Contact SceneShift | Book an AI Automation Call",
    description:
      "Contact SceneShift to discuss lead capture, AI reception, CRM follow-up, missed-call text back, review generation, and growth automation.",
    priority: "0.7",
    changefreq: "monthly",
    schemaType: "ContactPage",
  },
];

async function loadSnapshotRoutes() {
  try {
    const raw = await readFile(
      join(rootDir, "scripts", "data", "route-snapshot.json"),
      "utf8",
    );
    const snapshot = JSON.parse(raw);
    return snapshot.map((r) => ({
      path: r.path,
      key: r.path.replace(/^\//, "").replace(/\//g, "_") || "home",
      title: r.title,
      description: r.description,
      priority: typeof r.priority === "number" ? r.priority.toFixed(1) : "0.5",
      changefreq: r.changefreq ?? "monthly",
      schemaType: "WebPage",
      indexable: r.index !== false,
      jsonLd: r.jsonLd,
    }));
  } catch {
    return [];
  }
}

const snapshotRoutes = await loadSnapshotRoutes();

/**
 * Combined indexable canonical routes. Non-indexable snapshot entries are
 * surfaced separately so they can be included in prerender but excluded
 * from sitemap.xml and IndexNow submissions.
 */
export const canonicalRoutes = [
  ...baseCanonicalRoutes.map((r) => ({ ...r, indexable: true })),
  ...snapshotRoutes.filter((r) => r.indexable),
];

/** Routes that are prerendered but ship `noindex,follow`. */
export const noindexRoutes = snapshotRoutes.filter((r) => !r.indexable);

/** Routes prerendered to disk (both indexable and noindex). */
export const prerenderRoutes = [...canonicalRoutes, ...noindexRoutes];

export const disallowedPaths = [
  "/account",
  "/cart",
  "/checkout",
  "/gallery-grid",
  "/gallery-masonry",
  "/index",
  "/index1",
  "/index2",
  "/index3",
  "/index4",
  "/index5",
  "/index6",
  "/index7",
  "/index8",
  "/index9",
  "/index10",
  "/index11",
  "/index12",
  "/index13",
  "/index14",
  "/index15",
  "/index16",
  "/index17",
  "/project",
  "/project2",
  "/project-single",
  "/service-single",
  "/shop",
  "/shop-single",
  "/team",
  "/team-single",
  "/typography",
];

export function absoluteUrl(path = "/") {
  return new URL(path, site.url).toString();
}

export function absoluteAsset(path) {
  return new URL(path, site.url).toString();
}

export function escapeHtml(value) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}
